name: build-and-lint     #name 

# triggers: define when this workflow should run
# trigger on push to these branches
on:      # triggers or define when this workflow should run
  push:
    branches: [master, CI]
  pull_request:
    branches: [master, CI]

    # define a job (multiple jobs also) to be run in this workflow
jobs:
  build-and-lint:      
    runs-on: ubuntu-latest    # ubuntu environment which are given by github

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node    # setting up node environment 
        uses: actions/setup-node@v3
        with:
          node-version: 20 

      - name: Install backend dependencies   # installing dependencies for backend
        working-directory: server
        run: npm ci

      - name: Lint backend      # linting backend code
        working-directory: server
        run: npm run lint -- --max-warnings=0

      - name: Install frontend dependencies   # installing dependencies for frontend
        working-directory: client
        run: npm ci

      - name: Lint frontend      # linting frontend code
        working-directory: client
        run: npm run lint -- --max-warnings=0

      - name: Build backend image
        run: docker build -t backend ./server

      - name: Build frontend image
        run: docker build -t frontend ./client

  